kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang
  commands:
  - go test -coverprofile coverage.out ./... && go tool cover -func coverage.out
  - go build app.go

trigger:
  event:
  - push
  branch:
  - docker

