kind: pipeline
type: docker
name: golangapi

steps:
- name: build
  image: golang
  commands:
  - go test -coverprofile coverage.out ./... && go tool cover -func coverage.out
  - go build app.go
  
- name: push
  image: docker
  commands:
  - docker build -t golang-api-$(git rev-parse --short HEAD) .
  

trigger:
  event:
  - push
  branch:
  - docker

