kind: pipeline
type: docker
name: golangapi

steps:
- name: test
  image: golang
  commands:
  - go test -coverprofile coverage.out ./... && go tool cover -func coverage.out
  
- name: build
  image: golang
  commands:
  - go build app.go
  - echo -n "docker-"${DRONE_COMMIT_SHA:0:7}

- name: docker
  image: plugins/docker
  settings:
    username: 
      from_secret: DOCKER_USERNAME
    password:
      from_password: DOCKER_PASSWORD
    repo: bhautikimp/golangapi

trigger:
  event:
  - push
  branch:
  - docker

