# This pipeline executed when any changes push to docker
# This pipeline test the go.

kind: pipeline
type: docker
name: golangapiDevelopment

steps:
- name: preSlackNotitification
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
  template: build {{repo.name}} / {{build.branch}} - {{build.number}} has started for CI!
  when:
    branch:
    - *

- name: test
  image: golang
  commands:
  - go test -coverprofile coverage.out ./... && go tool cover -func coverage.out
  when:
    branch:
    - *

- name: docker
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: bhautikimp/golangapi
    build_args:
      - MODE=docker
  when:
    branch:
    - master
    - develop

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
  template: >
      {{#success build.status}}
        build {{repo.name}} / {{build.branch}} - {{build.number}} successed!
      {{else}}
        build {{repo.name}} / {{build.branch}} - {{build.number}} failed!
      {{/success}}
  when:
    status: [success, fail]

