repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-case-conflict
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: mixed-line-ending
  - id: no-commit-to-branch
    args: [--branch, master]
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.1
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-imports
    - id: go-cyclo
      args: [-over=15]
    - id: golangci-lint
    - id: go-critic
    - id: go-mod-tidy
    - id: go-mod-vendor
- repo: local
  hooks:
  - id: go-test
    name: "go-test"
    entry: hooks/go-test.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `go-test`, requires https://github.com/gotestyourself/gotestsum"
