version: "3.8"
services:
  postgresdb:
    image: postgres:15.2-alpine
    container_name: golang-api-postgresdb
    environment:
      POSTGRES_USER: golang-api
      POSTGRES_PASSWORD: golang-api
      POSTGRES_DB: golang-api
      POSTGRES_MULTIPLE_DATABASES: '"kratos-db"'
    ports:
    - 5432:5432
    volumes:
      - ./pkg/kratos/kratos-pg-init-script:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
    environment:
    - ADMINER_DEFAULT_SERVER=postgresdb
    depends_on:
    - postgresdb

  kratos_migrate:
    image: oryd/kratos:v1.0.0
    profiles: [kratos]
    environment:
      - DSN=postgres://golang-api:golang-api@postgresdb:5432/kratos-db?sslmode=disable
      - LOG_LEVEL=trace
    command: migrate sql -e --yes
    restart: on-failure
    depends_on:
      - postgresdb

  kratos:
    image: oryd/kratos:v1.0.0
    profiles: [kratos]
    ports:
      - '4433:${SERVE_PUBLIC_PORT:-4433}' # public
      - '4434:${SERVE_ADMIN_PORT:-4434}' # admin
    environment:
      - LOG_LEVEL=trace
    env_file:
      - .env

    command: serve -c /etc/config/kratos/kratos.yml

    restart: always
    depends_on:
      - postgresdb
      - kratos_migrate
    volumes:
      - "./pkg/kratos:/etc/config/kratos"

volumes:
  pgdata:
