version: "3.8"
services:
  postgresdb:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: golang-api
      POSTGRES_PASSWORD: golang-api
      POSTGRES_DB: golang-api
    ports:
    - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
    environment: 
    - ADMINER_DEFAULT_SERVER=postgresdb
    depends_on:
    - postgresdb

volumes:
  pgdata:
