version: "3.7"
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  postgresdb:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: golang-api
      POSTGRES_PASSWORD: golang-api
      POSTGRES_DB: golang-api
    ports:
      - 5432:5432
